name: tekaly_sembast_synced_test
description: Testing sembast_synced
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  sembast: ">=3.8.5+1"
  tekaly_sembast_synced:
    git:
      url: https://github.com/tekartikprj/tekaly
      path: packages/sembast_synced
  dev_test: ">=1.0.1"
  tekartik_app_cv_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_sembast
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.2"
resolution: workspace
