# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "flutter_packages/file_download"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "flutter_packages/firestore_explorer"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/file_download_web"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/firestore_synced"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/sdb_synced"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/sdb_synced_test"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/sembast_synced"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/sembast_synced_rpc"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/sembast_synced_test"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/tekaly_assets"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/tekaly_media_cache"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/tekaly_stat"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "test/firestore_explorer_test_app"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
