name: tekaly_firestore_synced
description: Collection accessed offline and synchronized with minimal read
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
  tekaly_sembast_synced:
    git:
      url: https://github.com/tekartikprj/tekaly
      path: packages/sembast_synced
  tekartik_app_cv_firestore:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_firestore
  tekartik_app_sembast_firestore_type_adapters:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_sembast_firestore_type_adapters
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
  # path: ^1.8.0

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.2"
resolution: workspace
