name: tekaly_assets
description: Common tekaly assets
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.2"
resolution: workspace
