name: tekaly_file_download_web
description: File download for web.
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  web: ">=1.1.1"
  path: ">=1.9.1"
  pub_semver: ">=2.2.0"
  test: ">=1.26.2"
  tekartik_platform_browser:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_browser
    version: '>=0.2.1'
dev_dependencies:
  build_runner: ">=2.9.0"
  build_web_compilers: ">=4.3.2"
  lints: ">=6.0.0"
resolution: workspace
