name: tekaly_stat
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
  cv: ">=1.1.10"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
  tekartik_firebase_storage_fs:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_fs
  tekartik_app_cv_firestore:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_firestore
  # path: ^1.8.0

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.2"
resolution: workspace
