name: tekaly_sembast_synced_rpc
description: RPC solution
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  tekaly_sembast_synced:
    git:
      url: https://github.com/tekartikprj/tekaly
      path: packages/sembast_synced
  tekaly_sembast_synced_test:
    git:
      url: https://github.com/tekartikprj/tekaly.git
      path: packages/sembast_synced_test
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_rpc:
    git:
      url: https://github.com/tekartik/rpc.dart
      path: packages/rpc
  tekartik_web_socket:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket
  tkcms_common:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      path: packages/tkcms_common
  # path: ^1.8.0

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.2"
resolution: workspace
