name: tekaly_media_cache
description: A simple media cache
version: 1.0.0
publish_to:  none

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ">=1.9.1"
  sembast: ">=3.8.5+1"
  fs_shim: ">=2.4.0"
  tekartik_app_cv_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_sembast
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_http
  tekartik_app_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_sembast
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart


dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.2"
resolution: workspace
